name: Pets
main: LostTeam\main
version: 1.0.0
api: [1.13.1, 2.0.0]
description: ""
author: "LostTeam"

Permissions:
  pets.command:
    default: true
    children:
      pets.command.list:
        default: true
      pets.command.help:
        default: true
      pets.command.cycle:
        default: true
      pets.command.clear:
        default: op
