name: Pets
main: LostTeam\main
version: 1.0.0
api: [1.13.1, 2.0.0]
description: ""
author: "LostTeam"

Permissions:
  pets.command.*:
    default: op
    children:
      pets.command.list:
        default: true
      pets.command.help:
        default: true
  pets.type.*:
    default: op
    children:
      pets.type.dog
      pets.type.chicken
      pets.type.ocelot
      pets.type.pig
      pets.type.magma
      pets.type.rabbit
      pets.type.bat
      pet.type.silverfish
      pets.type.blaze
